version: '2.4'

networks: {}

volumes:
  resin-data: {}

services:
  # https://github.com/mcuadros/ofelia
  iwait:
    image: mcuadros/ofelia:v0.3.7
    depends_on:
      - ifeed
    tty: true
    command: daemon --docker
    restart: unless-stopped
    labels:
      io.balena.features.balena-socket: '1'
      ofelia.job-local.restart-self.schedule: "@hourly"
      # FIXME: restart container to pick up new ifeed container name
      ofelia.job-local.restart-self.command: "kill -s SIGTERM 1"

  ifeed:
    build:
      context: ifeed
    tty: true
    restart: unless-stopped
    volumes:
      - 'resin-data:/data'
    entrypoint:
      - /bin/bash
      - -c
    command:
      - |
        set -axe

        function cleanup() {
            sleep infinity
        }
        trap cleanup EXIT

        exec ./main.py "$@"

    devices:
      - /dev/gpiomem
      - /dev/mem
    labels:
      ofelia.enabled: 'true'
      ofelia.job-exec.feed.schedule: '0 6 * * *'
      ofelia.job-exec.feed.command: "/bin/bash -c 'pgrep python3.10 | xargs kill -s USR2'"
      io.balena.features.sysfs: '1'
      io.resin.features.kernel-modules: '1'
      io.balena.update.strategy: 'kill-then-download'

  iwatch:
    build:
      context: iwatch
    tty: true
    restart: unless-stopped
    entrypoint:
      - /bin/bash
      - -c
    command:
      - |
        set -axe

        function cleanup() {
            sleep infinity
        }
        trap cleanup EXIT

        H264_PROFILE=${H264_PROFILE:-baseline}
        VIDEO_WIDTH=${VIDEO_WIDTH:-640}
        VIDEO_HEIGHT=${VIDEO_HEIGHT:-320}
        VIDEO_FRAMERATE=${VIDEO_FRAMERATE:-5}
        VIDEO_BITRATE=${VIDEO_BITRATE:-100000}
        KEYFRAME_RATE=${KEYFRAME_RATE:-10}

        # audio not used
        AUDIO_SAMPLE_RATE=${AUDIO_SAMPLE_RATE:-2205}

        # https://medium.com/@allanlei/streaming-your-raspberrypi-camera-6ad02edcaae7
        if [[ -n "$RTMP_STREAM_URL" ]]; then
            exec raspivid -n -t 0 -fl -hf -o - \
              -w "${VIDEO_WIDTH}" \
              -h "${VIDEO_HEIGHT}" \
              -fps "${VIDEO_FRAMERATE}" \
              -b "${VIDEO_BITRATE}" \
              -pf "${H264_PROFILE}" \
              -g "${KEYFRAME_RATE}" \
              | ffmpeg \
              -f lavfi \
              -i "anullsrc=channel_layout=stereo:sample_rate=${AUDIO_SAMPLE_RATE}" \
              -i pipe:0 \
              -c:v copy \
              -c:a aac \
              -strict experimental \
              -f flv "${RTMP_STREAM_URL}" \
              "$@"
        fi

    devices:
      - /dev/vchiq
      - /dev/video0
      - /dev/dma_heap
      - /dev/vcsm-cma
    labels:
      io.balena.features.sysfs: '1'
      io.resin.features.kernel-modules: '1'
      io.balena.update.strategy: 'kill-then-download'
